---
- name: Install Harbor
  import_tasks: install.yml
  tags: install

- name: Manage users
  import_tasks: users_management.yml
  tags: users

- name: Add Docker Hub replicaiton
  import_tasks: replication.yml
  tags: replication

- name: Manage projects retention policy
  import_tasks: project_retention_policy_management.yml
  tags: retention_policy
