---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include harbor_ansible_role"
      include_role:
        name: "harbor_ansible_role"
      vars:
        harbor_projects:
          - project_name: first_project
            public: "true"
          - project_name: "secondproject"
            public: "false"
        harbor_users:
          - username: "user_one"
            email: "email@mail.com"
            password: "Harboruser12345"
            realname: "user one"
            comment: "void"
            projects:
              - project_name: first_project
                role_id: 2
              - project_name: secondproject
                role_id: 3
          - username: "second_one"
            email: "email_two@mail.com"
            password: "Harboruser12345"
            realname: "user two"
            comment: "void"
            projects:
              - project_name: first_project
                role_id: 2
              - project_name: secondproject
                role_id: 3
          - username: "third_one"
            email: "email_three@mail.com"
            password: "Harboruser12345"
            realname: "user three"
            comment: "void"
            projects:
              - project_name: first_project
                role_id: 2
              - project_name: secondproject
                role_id: 3
